/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
<<<<<<< HEAD
import { Route as ProtectedMyFeedsRouteImport } from './routes/_protected/my-feeds'
import { Route as AuthenticatedLoginRouteImport } from './routes/_authenticated/login'
=======
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as AuthenticatedLoginRouteImport } from './routes/_authenticated/login'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as ProtectedProfileEditProfileRouteImport } from './routes/_protected/profile/edit-profile'
>>>>>>> 8a697c1 (init)

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const ProtectedMyFeedsRoute = ProtectedMyFeedsRouteImport.update({
  id: '/my-feeds',
  path: '/my-feeds',
=======
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
>>>>>>> 8a697c1 (init)
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthenticatedLoginRoute = AuthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticatedRoute,
} as any)
<<<<<<< HEAD
=======
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileEditProfileRoute =
  ProtectedProfileEditProfileRouteImport.update({
    id: '/profile/edit-profile',
    path: '/profile/edit-profile',
    getParentRoute: () => ProtectedRoute,
  } as any)
>>>>>>> 8a697c1 (init)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthenticatedLoginRoute
<<<<<<< HEAD
  '/my-feeds': typeof ProtectedMyFeedsRoute
=======
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/profile/edit-profile': typeof ProtectedProfileEditProfileRoute
  '/profile/': typeof ProtectedProfileIndexRoute
>>>>>>> 8a697c1 (init)
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthenticatedLoginRoute
<<<<<<< HEAD
  '/my-feeds': typeof ProtectedMyFeedsRoute
=======
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/profile/edit-profile': typeof ProtectedProfileEditProfileRoute
  '/profile': typeof ProtectedProfileIndexRoute
>>>>>>> 8a697c1 (init)
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_authenticated/login': typeof AuthenticatedLoginRoute
<<<<<<< HEAD
  '/_protected/my-feeds': typeof ProtectedMyFeedsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/login' | '/my-feeds'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/login' | '/my-feeds'
=======
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/profile/edit-profile': typeof ProtectedProfileEditProfileRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/profile/edit-profile'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/profile/edit-profile'
    | '/profile'
>>>>>>> 8a697c1 (init)
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/_protected'
    | '/_authenticated/login'
<<<<<<< HEAD
    | '/_protected/my-feeds'
=======
    | '/_protected/dashboard'
    | '/_protected/settings'
    | '/_protected/profile/edit-profile'
    | '/_protected/profile/'
>>>>>>> 8a697c1 (init)
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/_protected/my-feeds': {
      id: '/_protected/my-feeds'
      path: '/my-feeds'
      fullPath: '/my-feeds'
      preLoaderRoute: typeof ProtectedMyFeedsRouteImport
=======
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
>>>>>>> 8a697c1 (init)
      parentRoute: typeof ProtectedRoute
    }
    '/_authenticated/login': {
      id: '/_authenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticatedLoginRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
<<<<<<< HEAD
=======
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile/edit-profile': {
      id: '/_protected/profile/edit-profile'
      path: '/profile/edit-profile'
      fullPath: '/profile/edit-profile'
      preLoaderRoute: typeof ProtectedProfileEditProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
>>>>>>> 8a697c1 (init)
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLoginRoute: typeof AuthenticatedLoginRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLoginRoute: AuthenticatedLoginRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ProtectedRouteChildren {
<<<<<<< HEAD
  ProtectedMyFeedsRoute: typeof ProtectedMyFeedsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedMyFeedsRoute: ProtectedMyFeedsRoute,
=======
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedProfileEditProfileRoute: typeof ProtectedProfileEditProfileRoute
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedProfileEditProfileRoute: ProtectedProfileEditProfileRoute,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
>>>>>>> 8a697c1 (init)
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
