/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedMyFeedsRouteImport } from './routes/_protected/my-feeds'
import { Route as AuthenticatedLoginRouteImport } from './routes/_authenticated/login'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedMyFeedsRoute = ProtectedMyFeedsRouteImport.update({
  id: '/my-feeds',
  path: '/my-feeds',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthenticatedLoginRoute = AuthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthenticatedLoginRoute
  '/my-feeds': typeof ProtectedMyFeedsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthenticatedLoginRoute
  '/my-feeds': typeof ProtectedMyFeedsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_authenticated/login': typeof AuthenticatedLoginRoute
  '/_protected/my-feeds': typeof ProtectedMyFeedsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/login' | '/my-feeds'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/login' | '/my-feeds'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/_protected'
    | '/_authenticated/login'
    | '/_protected/my-feeds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/my-feeds': {
      id: '/_protected/my-feeds'
      path: '/my-feeds'
      fullPath: '/my-feeds'
      preLoaderRoute: typeof ProtectedMyFeedsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_authenticated/login': {
      id: '/_authenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticatedLoginRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLoginRoute: typeof AuthenticatedLoginRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLoginRoute: AuthenticatedLoginRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedMyFeedsRoute: typeof ProtectedMyFeedsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedMyFeedsRoute: ProtectedMyFeedsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
